Changes to configure on Derecho with C and Fortran NetCDF builds in different locations

diff --git a/models/utils/pio/configure b/models/utils/pio/configure
--- a/models/utils/pio/configure
+++ b/models/utils/pio/configure
@@ -7749,30 +7749,30 @@ fi
 
 if test "$USE_NETCDF" = "yes"
   then
-       if test -n "$NETCDF_PATH"
-         then echo "using NETCDF_PATH from environment"
-         else NETCDF_PATH=/usr/local/netcdf
-              { echo "$as_me:$LINENO: WARNING: NETCDF_PATH not found in environment, \
-                           defaulting to $NETCDF_PATH" >&5
-echo "$as_me: WARNING: NETCDF_PATH not found in environment, \
-                           defaulting to $NETCDF_PATH" >&2;}
-       fi
+#        if test -n "$NETCDF_PATH"
+#          then echo "using NETCDF_PATH from environment"
+#          else NETCDF_PATH=/usr/local/netcdf
+#               { echo "$as_me:$LINENO: WARNING: NETCDF_PATH not found in environment, \
+#                            defaulting to $NETCDF_PATH" >&5
+# echo "$as_me: WARNING: NETCDF_PATH not found in environment, \
+#                            defaulting to $NETCDF_PATH" >&2;}
+#        fi
 
        PDEFS="$PDEFS -D_NETCDF"
-       PINCS="$PINCS -I$NETCDF_PATH/include"
-       PLIBS="$PLIBS -L$NETCDF_PATH/lib -lnetcdf"
+       PINCS="$PINCS -I$netcdf_c_ROOT/include -I$netcdf_fortran_ROOT/include "
+       PLIBS="$PLIBS -L$netcdf_c_ROOT/lib -lnetcdf -L$netcdf_fortran_ROOT/lib -lnetcdff"
 
-       if test ! -f $NETCDF_PATH/include/netcdf.mod && \
-          test ! -f $NETCDF_PATH/include/NETCDF.mod
-         then { { echo "$as_me:$LINENO: error: netcdf.mod not found in NETCDF_PATH/include \
+       if test ! -f $netcdf_fortran_ROOT/include/netcdf.mod && \
+          test ! -f $netcdf_fortran_ROOT/include/NETCDF.mod
+         then { { echo "$as_me:$LINENO: error: netcdf.mod not found in netcdf_fortran_ROOT/include \
                             check the environment variable NETCDF_PATH" >&5
-echo "$as_me: error: netcdf.mod not found in NETCDF_PATH/include \
+echo "$as_me: error: netcdf.mod not found in netcdf_fortran_ROOT/include \
                             check the environment variable NETCDF_PATH" >&2;}
    { (exit 1); exit 1; }; }
        fi
 
-       if test ! -f $NETCDF_PATH/lib/libnetcdf.a
-         then { { echo "$as_me:$LINENO: error: libnetcdf.a not found in NETCDF_PATH/lib \
+       if test ! -f $netcdf_c_ROOT/lib/libnetcdf.a
+         then { { echo "$as_me:$LINENO: error: libnetcdf.a not found in netcdf_c_ROOT/lib \
                             check the environment variable NETCDF_PATH " >&5
 echo "$as_me: error: libnetcdf.a not found in NETCDF_PATH/lib \
                             check the environment variable NETCDF_PATH " >&2;}
@@ -7788,7 +7788,7 @@ if test "$USE_NETCDF4" = "yes"
    PDEFS="$PDEFS -D_NETCDF4"
    if test -e "$NETCDF_PATH/lib/pkgconfig/"
      then
-     export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$NETCDF_PATH/lib/pkgconfig/"
+     export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$netcdf_c_ROOT/lib/pkgconfig/:$netcdf_fortran_ROOT/lib/pkgconfig/"
 
 
 if test "x$ac_cv_env_PKG_CONFIG_set" != "xset"; then
